services:
  eltop:
    network_mode: "host"
    # image: ksobitov/eltop:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eltop
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'ASPNETCORE_URLS=http://+:80'
      - 'ConnectionStrings__Default=User Id=${POSTGRESS_USER};Password=${POSTGRESS_PASSWORD};Host=${POSTGRESS_HOST};Port=${POSTGRESS_PORT};Database=${POSTGRESS_DBNAME};'
      - 'JwtSettings:SecretKey=my top key is eltop but this key is very difficult for example I need 512 bit greater than how we do it ?'
      - 'DatabaseProviderConfiguration:ProviderType=PostgreSQL'
    ports:
      - '5080:80'
